### PR TITLE
Add test for cvmfs_server check failures

### LINKED ISSUE #26: Add test for cvmfs_server check failures
If there is a "check_status" entry in .cvmfs_status.json with the contents "failed", then flag that as an error.

### PR DESCRIPTION
**Pull request by edytuk**
Fixes #26

### CODE REVIEW

**Comment by edytuk** [comment]
I was not able to find `check_status` in order to test this

**Comment by DrDaveD** [comment]
Test it against https://oasis-replica-itb.opensciencegrid.org.  You can define a remote server in /etc/cvmfsmon/api.conf (although it will be very slow if run from a machine at CERN).  I see it has one repo with a failure, so you can test that aspect as well.

**Comment by edytuk** [comment]
I tested it against your provided server.
```
{
"CRITICAL":
    {
        "gc": [{"msg": "error: cvmfs_server failure", "repo": "oasis.opensciencegrid.org"}],
        "updated": [{"msg": "error: cvmfs_server failure", "repo": "oasis.opensciencegrid.org"}]
    }
}
```

**Comment by DrDaveD** [comment]
That's the right repo for the check_status failure, but the wrong results.  We don't want to flag errors with updated and gc.  Please instead add another "check" test.  Make it be WARNING if any repository has a failed message.

**Comment by edytuk** [comment]
I created a new test

**Review by DrDaveD — CHANGES_REQUESTED** [review]
Overall the code looks good, but it should be called "check" and not "server".  The failure is not on all of cvmfs_server, it is specifically on "cvmfs_server check" operations.  This a repository check, an audit.  The name "server" implies to me that the service isn't working properly, and that's not the case.

**Review by DrDaveD — APPROVED** [review]

**Pull request merged**
